// export default {
//   questions: [],
//   userVotes: {},
//   answers: {},
//   userAnswerVotes: {},
//   tags: [],
// };
export default {
  questions: [
    {
      questionId: 0,
      author: "Bobert",
      content: "Have you ever heard the wolf cry to the blue corn moon?",
      upVotes: 13,
      downVotes: 3,
      answerIdList: [0, 1],
      timeStamp: 1599055200000,
      tags: [0],
    },
    {
      questionId: 1,
      author: "MaryAnn",
      content:
        "Have you ever asked the grinning bobcat why he grinned? Have you ever asked the grinning bobcat why he grinned? Have you ever asked the grinning bobcat why he grinned? Have you ever asked the grinning bobcat why he grinned? Have you ever asked the grinning bobcat why he grinned? Well I haven't, but I would bloody well like to one day.",
      upVotes: 22,
      downVotes: 0,
      answerIdList: [],
      timeStamp: 1599155200000,
      tags: [1],
    },
    {
      questionId: 2,
      author: "EvilLizard",
      content: "Can you sing with all the voices of the mountains?",
      upVotes: 17,
      downVotes: 8,
      answerIdList: [],
      hansardLink:
        "https://hansard.parliament.vic.gov.au/isysquery/14b80f19-378a-4d9d-864a-88f25c6a292d/2/doc/",
      timeStamp: 1599255200000,
      tags: [2],
    },
    {
      questionId: 3,
      author: "TheFonz",
      content: "Can you paint with all the colors of the wind?",
      upVotes: 1,
      downVotes: 11,
      answerIdList: [2],
      timeStamp: 1599355200000,
      tags: [2, 3],
    },
    {
      questionId: 4,
      author: "EvilLizard",
      content: "Where's all the rum gone?",
      upVotes: 2,
      downVotes: 11,
      answerIdList: [],
      timeStamp: 1599455200000,
      tags: [4],
    },
    {
      questionId: 5,
      author: "FuelGuzzler",
      content:
        "Why is this question so long? I just don't understand why it has to be so long. It is truly excessive",
      upVotes: 0,
      downVotes: 30,
      answerIdList: [],
      timeStamp: 1599555200000,
      tags: [5, 6, 7],
    },
    {
      questionId: 6,
      author: "Cleopatra",
      content: "Why has all the laughter ceased?",
      upVotes: 1,
      downVotes: 37,
      answerIdList: [],
      timeStamp: 1599555200000,
      tags: [0, 7],
    },
  ],
  userVotes: {
    0: 1,
    1: 0,
    2: -1,
    3: 0,
    4: 0,
    5: -1,
    6: 1,
  },
  answers: {
    0: {
      answerId: 0,
      author: "Aniel_Dandrews",
      content:
        "Yes, I believe there is a very good reason for this. The birds are the ones responsible",
      upVotes: 2,
      downVotes: 4,
      timeStamp: 1599655200000,
    },
    1: {
      answerId: 1,
      author: "Ruthilda_McGrubber",
      content:
        "This is an unbecoming issue. Here are my favourite kinds of meat: Turkey andouille tongue pork belly burgdoggen ground round, bresaola shank doner. Frankfurter sausage drumstick alcatra short ribs jerky, ham hock pork buffalo leberkas. Sausage picanha turk",
      upVotes: 6,
      downVotes: 3,
      timeStamp: 1599755200000,
    },
    2: {
      answerId: 2,
      author: "BillBiffkin",
      content:
        "I'm baby chia street artof blue marfa beard edison bulb semiotics enamel pin glossier. Authentic echo park vinyl.",
      upVotes: 9,
      downVotes: 7,
      timeStamp: 1599805200000,
    },
  },
  userAnswerVotes: { 0: 0, 1: 1, 2: -1 },
  tags: [
    { name: "Covid", tagID: 0, used: 123 },
    { name: "elections", tagID: 1, used: 11 },
    { name: "DanAndrews", tagID: 2, used: 53 },
    { name: "DamConstruction", tagID: 3, used: 153 },
    { name: "ScottMorrison", tagID: 4, used: 89 },
    { name: "LGBT", tagID: 5, used: 68 },
    { name: "publicHealth", tagID: 6, used: 12 },
    { name: "sports", tagID: 7, used: 33 },
  ],
};
